version: '3'

services:
  rms_gateway_service:
    image: rms_gateway_image:latest
    container_name: rms_gateway_container
    volumes:
      - .:/rms_gateway_volume
    ports:
      - "8002:8002"
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    networks:
      rms_network:
          ipv4_address:  172.18.0.3

networks:
  rms_network:
    external: true