version: '3'

services:
  rms_gateway_service:
    image: rms_gateway_image:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: rms_gateway_container
    volumes:
      - .:/rms_gateway_volume
    ports:
      - "8002:8000"

networks:
    default:
        external:
            name: rms_network